# Project metadata
sonar.projectKey=sdmo
sonar.projectName=sdmo
sonar.projectVersion=1.0

# Source code directory
sonar.sources=.

# Ignore test files
sonar.exclusions=**/unit_tests.py,**/__pycache__/**

# Encoding
sonar.sourceEncoding=UTF-8

# Python setup
sonar.language=py

# Optional: include test coverage (if generated)
sonar.python.coverage.reportPaths=coverage.xml
